### ISSUE TITLE
[1.4.7 (43)] Samsung Galaxy Note 4 / 6.0.1 - Added sticker is not displayed on "Preview".

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#403]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select few motifs from "Instagram".
3: Skip music and proceed to "Create" screen.
4: Add filter and sticker and export the lomotif.
5: Load recently created lomotif project.
6: Check if sticker is not displayed on preview.

Expected result: Added sticker should be displayed on "Preview".

Actual result: Added sticker is not displayed on "Preview".

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.7 (43) on LG Nexus 5X Android 6.0.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.5.0-r1 (49)] on Samsung Galaxy Note 4 / 6.0.1.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r1 (49)] on Asus Zenfone Go / Android 5.1
1. Sticker issue is applicable for all camera roll images (not only for Instagram images).
2. This issue is also reproducible when user apply sticker and save lomotif by clicking on Home button. No need to Export lomotif and then load it again.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.5.0-r4 (52)] on Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 and Samsung Galaxy J7 / 6.0.1.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r5 (53)].

Close for Build 1.5.0-r5.
